# Generated by Django 4.0.5 on 2022-08-03 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_order_student'),
        ('myapp', '0006_alter_topic_length'),
    ]

    operations = [
    ]
